### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by 0xh3LL0** [Elastic1/piccoma-downloader#1]
is it because there is no cortana on my windows?
![Untitled234](https://user-images.githubusercontent.com/23132217/132942419-953a3b0b-d967-4679-8d76-5b9f97e61636.png)

**Comment by 0xh3LL0** [comment]
i got the same error,
is this script only support for paid chapters? or there should be another requirements?
i only have free account, so i assume it cant download free chapters...?

**Comment by Elastic1** [comment]
Are you sure you can login from https://piccoma.com/web/acc/email/signin? This project only supports login with an email address.

By the way, you can download free chapters with this script. Currently, I download the webtoon by chapter and the manga version by volume.

**Comment by 0xh3LL0** [comment]
yes, i can login from there...

`manga version by volume`
then, i guess, this also a problem, since i can only wait 1 chapter a day, and a day later the previous chapter is expired, so there is no way i own the whole volume

this is just selfish request of mine, but can you add/make your script to download only chapter instead volume?
maybe something like this:
node piccoma.mjs https://piccoma.com/link-to-chapter

**Comment by Elastic1** [comment]
I add few options in new release. [options](https://github.com/Elastic1/piccoma-downloader#options)

Maybe your command will looks like. (specify 0 in `timeout` to avoid timeout error)
```
node piccoma.mjs --manga chapter --timeout 0
```

**Comment by 0xh3LL0** [comment]
it works, thank you very much!
![Screenshot (989)](https://user-images.githubusercontent.com/23132217/133538305-f798fb8d-9376-4d0c-9682-c5296fbd455f.png)

**Comment by 0xh3LL0** [comment]
another question,
if, tomorrow i want to download again (next chapter), will the downloaded (current) chapter skipped?

**Comment by Elastic1** [comment]
I'm glad to hear it's working.

yes, If chapter directory exists, it will skip it.

**Comment by 0xh3LL0** [comment]
once again, thank you very much,

i can safely close this issue now.
