### ISSUE TITLE
connection not working ?

### ISSUE THREAD

**Issue by alex0064** [Elastic1/piccoma-downloader#10]
Hi, thanks for the project
However, when I download the .exe and I put my id and password it closes by itself. Is it compatible with windows 10?

**Comment by alex0064** [comment]
I understood that it only accepts chapter-url for the French version but the problem is that when you open the .exe you have to put the mail and passworld and when they are put the program always closes automatically...

**Comment by Elastic1** [comment]
French version seems to have changed a lot since before.
Currently it is difficult to download and may not be supported.
