### ISSUE TITLE
Support French version

### ISSUE THREAD

**Issue by Elastic1** [Elastic1/piccoma-downloader#11]
Currently, downloads from the FR version are not easy to process with raw image data only (my poor programming skills😅).
Therefore, to simplify development, I decided to let the headless browser run in the background for FR version and support Windows only.

(*The JP version is still the same as before.)

**Comment by alex0064** [comment]
ok I see, too bad :(

**Comment by Elastic1** [comment]
Supported now on new release.

https://github.com/Elastic1/piccoma-downloader/releases
