### ISSUE TITLE
failed to get image list

### ISSUE THREAD

**Issue by 0xh3LL0** [Elastic1/piccoma-downloader#12]
book in question https://piccoma.com/web/product/59707?etype=episode
already download ch 1.1-2.1 which is free but failed at ch 2.2
already use my ticket, have 71 hours remaining
![Untitled2](https://user-images.githubusercontent.com/23132217/187372569-914f2d91-d4cb-4d32-894f-29b6444943d1.png)

![Untitled3](https://user-images.githubusercontent.com/23132217/187372776-ea6c3f81-1a5c-466c-8a7c-e52dcb9d2d87.png)

**Comment by 0xh3LL0** [comment]
idk if this help but here is the log when i run without --chapter-url and choose manually
[log.txt](https://github.com/Elastic1/piccoma-downloader/files/9450597/log.txt)

**Comment by Elastic1** [comment]
There seems to be a bug in the login process when using `--chapter-url`

The command executed without `--chapter-url` seems to be missing the `--manga chapter` option. This tool downloads volumes by default for non-Webtoon.
