### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by Blackfairie** [Elastic1/piccoma-downloader#13]
Hello, all chapters that contain a special character or series whose title contains this character cannot be picked up.
characters in question: 
<
>
:
/
\
?
*
"
|

**Comment by Elastic1** [comment]
Can you give me an example of a URL for a chapters?

**Comment by Blackfairie** [comment]
> 

Yes sure, 
![Capture d’écran (2004)](https://user-images.githubusercontent.com/115415720/197347372-ca8c59f3-ac0d-411f-acd3-ba9500672a8a.png)

I have much more pictures, but only the chapters with special character don't work.
