### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by Kajiikaa** [Elastic1/piccoma-downloader#14]
Bonsoir, 

Pour votre scripte sur Piccoma, je sais qu'on peut choisir les séries qu'on veux avec espace. 
J'aimerais savoir si c'est possible de choisir les chapitres qu'on souhaite ? si non c'est possible de me donner une solution pour ? 

Merci :) 

Hello,

For your script on Piccoma, I know you can choose the series you want with a space.
I would like to know if it is possible to choose the chapters you want? If not, can you give me a solution?

Thanks :)

**Comment by Elastic1** [comment]
Maybe the `--chapter-url` option can help.
