### ISSUE TITLE
error since few weeks

### ISSUE THREAD

**Issue by Akhilia** [Elastic1/piccoma-downloader#16]
Hi,

since few weeks, this error occured for this entry.

![image](https://user-images.githubusercontent.com/99281317/204091204-eb319958-932c-4031-8a0e-42526d14e90c.png)

Others have no problem to download, it's the only one and until few weeks ago there was no error on it.
Could you take a look at it, please ? :)

Thanks :)

**Comment by Elastic1** [comment]
There seems to be a problem with the `node-pureimage` library. I have reported the problem and will apply it here as soon as it is fixed.
If it is not fixed after a few days (or weeks), the library may be changed.
