### ISSUE TITLE
Mangas Erro

### ISSUE THREAD

**Issue by Blackfairie** [Elastic1/piccoma-downloader#18]
We can't download purshased Mangas. The script don't recognize them, when they are only available in Volume.
![image](https://user-images.githubusercontent.com/115415720/205519680-194ef2b8-5473-4c36-bba3-6a5a24b8bb62.png)

**Comment by Elastic1** [comment]
fixed https://github.com/Elastic1/piccoma-downloader/commit/81dff8e2653f01c2ef4a86c06bb15eb80f6ff6d6
