### ISSUE TITLE
 create single executable file

### ISSUE THREAD

**Issue by Elastic1** [Elastic1/piccoma-downloader#2]
- [x] Use [axios](https://github.com/axios/axios)+[cheerio](https://github.com/cheeriojs/cheerio) instead of puppeteer
- [x] Replace node-canvas with [pure-image](https://github.com/joshmarinacci/node-pureimage/).
- [x] Make a single binary with [pkg](https://github.com/vercel/pkg/).

If there is a demand, i will make it.

**Comment by 0xh3LL0** [comment]
`If there is a demand, i will make it`
yes please.
