### ISSUE TITLE
またフォルダ作成できない

### ISSUE THREAD

**Issue by Yucie** [Elastic1/piccoma-downloader#20]
error occurred. retry  [Error: ENOENT: no such file or directory, mkdir 'D:\piccoma\manga\【全年齢版】ギラつき上司と偽装結婚!?\第14話'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\piccoma\\manga\\【全年齢版】ギラつき上司と偽装結婚!?\\第14話'
}
error occurred. retry  [Error: ENOENT: no such file or directory, mkdir 'D:\piccoma\manga\【全年齢版】ギラつき上司と偽装結婚!?\第15話'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\piccoma\\manga\\【全年齢版】ギラつき上司と偽装結婚!?\\第15話'
}
error occurred. retry  [Error: ENOENT: no such file or directory, mkdir 'D:\piccoma\manga\【全年齢版】ギラつき上司と偽装結婚!?\第15話'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\piccoma\\manga\\【全年齢版】ギラつき上司と偽装結婚!?\\第15話'
}
error occurred. retry  [Error: ENOENT: no such file or directory, mkdir 'D:\piccoma\manga\【全年齢版】ギラつき上司と偽装結婚!?\第96話'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\piccoma\\manga\\【全年齢版】ギラつき上司と偽装結婚!?\\第96話'
}
error occurred. retry  [Error: ENOENT: no such file or directory, mkdir 'D:\piccoma\manga\【全年齢版】ギラつき上司と偽装結婚!?\第96話'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\piccoma\\manga\\【全年齢版】ギラつき上司と偽装結婚!?\\第96話'

タイトルが”！？”付いたので、またフォルダ作成できなくなった。
修正お願いします。

**Comment by Elastic1** [comment]
修正しました😊 [v1.1.3](https://github.com/Elastic1/piccoma-downloader/releases/tag/v1.1.3)
