### ISSUE TITLE
No connection?

### ISSUE THREAD

**Issue by K4iserZ** [Elastic1/piccoma-downloader#23]
I selected the name series, says "accessing...." but then ends
![pic1](https://user-images.githubusercontent.com/105380141/214742310-0709e9a9-8627-441f-bc8f-eb27e4c808d4.png)

Am I doing something wrong?

**Comment by 0xh3LL0** [comment]
i tried just now, and it works

most likely there are no chapter to download,
this program won't download anything chapter already downloaded or folder with the chapter name already exist,
or the chapter you want to download is paid and you haven't bought it.

**Comment by K4iserZ** [comment]
I have bought it, however it seems my mistake was not using a VPN, now works, ty!
