### ISSUE TITLE
JPG doesn't work

### ISSUE THREAD

**Issue by Blackfairie** [Elastic1/piccoma-downloader#30]
I followed this code : piccoma.exe --mail mymail@gmail.com --password MyPasswordIsTooStrong --format jpg --quality 100 --type fr --all --out Piccoma JPG

But no images are downloaded and no files are created. However, the script does show that images are being downloaded when they are not.

I think it would be easier to integrate an option tab in the script so that you can choose the format, the quality and all the other options that this script has to offer.
![Screenshot ](https://user-images.githubusercontent.com/115415720/236828637-5d64e169-52ad-4c74-8f8a-d54bf683d6c0.jpg)

**Comment by Hachdog** [comment]
If you download a Manga (not a Smartoon - which has the red logo) chapter by chapter, make sure to add --manga chapter
Else nothing is downloaded

**Comment by Blackfairie** [comment]
I want to download a Smartoon.

**Comment by Hachdog** [comment]
> I want to download a Smartoon.

Did you put this Smartoon in your favorites? And did you buy or enable WUF (Wait Untill Free) for the chapter you want?
If you want you can you send me the link to the serie so I can try to see if it works with me

**Comment by Blackfairie** [comment]
> > I want to download a Smartoon.
> 
> Did you put this Smartoon in your favorites? And did you buy or enable WUF (Wait Untill Free) for the chapter you want? If you want you can you send me the link to the serie so I can try to see if it works with me

Yes, i know how to use the app the problem is that it doesn't makes JPG images but PNG images which are heavier than JPG.

**Comment by Hachdog** [comment]
> Yes, i know how to use the app the problem is that it doesn't makes JPG images but PNG images which are heavier than JPG.

Personally I never had issues getting JPG when using --format jpg setting.

Try with another version maybe 1.1.5

If you can't solve the problem, a solution would be to convert those PNG into JPG.  There's a batch for that on Irfanview. It's pretty easy and fast

N.B. Looking at your first post, you probably have noticed already, but if you set folder as "Piccoma JPG" the created folder will only be in "Piccoma". What is after the space isn't taken into account.
