### ISSUE TITLE
Can't login anymore (IP ban?)

### ISSUE THREAD

**Issue by Hachdog** [Elastic1/piccoma-downloader#31]
Hello, i'm having this issue for a couple of days on all (3) my accounts.
![Clipboard01](https://github.com/Elastic1/piccoma-downloader/assets/72262131/c18fd0a2-7c98-4191-ad73-10ae3ba84a13)
It is fixed by using a VPN so i'm wondering if i've been IP ban. I still have acces with my regular devices (phones, tablet) using the same internet connection.
If you have any idea.

**Comment by 0xh3LL0** [comment]
not ip ban,
piccoma only accessible from japan, using vpn is the only way for non japanese user now.
![Screenshot 2023-07-29 at 09-16-11 ピッコマ｜無料漫画・小説、新作コミックが毎日楽しめる！](https://github.com/Elastic1/piccoma-downloader/assets/23132217/1f7ed5a7-fb43-4a05-a4a4-74e479e5efc5)

**Comment by Hachdog** [comment]
> not ip ban, piccoma only accessible from japan, using vpn is the only way for non japanese user now. ![Screenshot 2023-07-29 at 09-16-11 ピッコマ｜無料漫画・小説、新作コミックが毎日楽しめる！](https://user-images.githubusercontent.com/23132217/256958821-1f7ed5a7-fb43-4a05-a4a4-74e479e5efc5.png)

There is a French version, piccoma.com/fr
IP ban is real.

**Comment by 0xh3LL0** [comment]
i guess you should close this issue then,
this issue is not even related to this program...
