### ISSUE TITLE
Login ok but nothing

### ISSUE THREAD

**Issue by Akhilia** [Elastic1/piccoma-downloader#32]
Hello,

I tried to log in this morning, but I can no longer see the series I have bookmarked.
All I have is this.
Do you have any idea what's wrong?
Knowing that until yesterday, I had no problem accessing the chapters.

Thanks in advance.

![probleme exe](https://github.com/Elastic1/piccoma-downloader/assets/99281317/5218c793-67ae-4c41-a28b-fb020ec85b2e)

**Comment by Akhilia** [comment]
As I'm using an older version (dated October 24, 2022), I downloaded the latest one to see if it wasn't just a version problem.
But I got the same result

**Comment by Lotucias** [comment]
I hae the same problem that Akhilia described.
Downloaded the last version with same result.

**Comment by Akhilia** [comment]
There seems to have been a change in the French title. (cf blackfairies post #33)
From "wait until free" to "prêt-à-lire".

**Comment by Akhilia** [comment]
> > There seems to have been a change in the French title. (cf blackfairies post #33) From "wait until free" to "prêt-à-lire".
> 
> I'm not really convinced by that since you can still download using url address. Which means the process still knows the difference between available/WUF chapters and locked ones

I must confess that i don't know how to dl with URL address... ^^

**Comment by Hachdog** [comment]
Ahah, you just need to add the command line --chapter-url and the url (obviously)

**Comment by Akhilia** [comment]
easier to say than do 🤣  (for me at least ^^)

**Comment by Hachdog** [comment]
> easier said than done rofl (for me at least ^^)

It looks like that
piccoma.exe --type fr --mail XXXX --password XXXX --chapter-url https://fr.piccoma.com/fr/viewer/XXXXXXX

;)

**Comment by Lotucias** [comment]
I tried to do the download manually but after a number of requests nothing started.
I feel like my internet connection has been banned because when I was trying to access my account via the website an error message was displayed while I can connect to it with the 5G of my phone.
I don't have more information currently, I would try from another connection if I have the opportunity but conclusion be careful if you go through the URL addresses.

**Comment by Hachdog** [comment]
> I tried to do the download manually but after a number of requests nothing started. I feel like my internet connection has been banned because when I was trying to access my account via the website an error message was displayed while I can connect to it with the 5G of my phone. I don't have more information currently, I would try from another connection if I have the opportunity but conclusion be careful if you go through the URL addresses.

As you may have seen in my previous issue post, if you connect too much you get IP ban. Solution is to renew you IP address (my ISP provides that option) use cellphone data or VPN.

**Comment by Akhilia** [comment]
> --mail XXXX --password XXXX --chapter-url https://fr.piccoma.com/fr/viewer/XXXXXXX

Where do you type all of these ? i try since yesterday but can't... 
I guess I've to wait the app problem to be fixed...

**Comment by Elastic1** [comment]
Fixed (#33)
