### ISSUE TITLE
Script is gone since the last update

### ISSUE THREAD

**Issue by Blackfairie** [Elastic1/piccoma-downloader#33]
They changed "Wait Until Free" to "Prêt-à-lire". That's could be the reasons of this issue.
https://gyazo.com/cc67c58ad81035987a021dcb1ee70d07

**Comment by Hachdog** [comment]
Shouldn't it show the bought chapters then?

**Comment by Blackfairie** [comment]
> Shouldn't it show the bought chapters then?

Liked chapters are not displayed. Probably since the last update of the application where they changed the names of the wait until free as I said above.

**Comment by Blackfairie** [comment]
> > > Shouldn't it show the bought chapters then?
> > 
> > 
> > Liked chapters are not displayed. Probably since the last update of the application where they changed the names of the wait until free as I said above.
> 
> I understood that. I'm pointing out that purchased chapters are not considered as WUF nor Prêt-a-lire. And Favorites were previously displayed even though there was nothing available to download. Also you can download using --url , it works.

Mhm ok, that's goo to know till the script isn't fixed. Thank you.

**Comment by Blackfairie** [comment]
> > > Shouldn't it show the bought chapters then?
> > 
> > 
> > Liked chapters are not displayed. Probably since the last update of the application where they changed the names of the wait until free as I said above.
> 
> I understood that. I'm pointing out that purchased chapters are not considered as WUF nor Prêt-a-lire. And Favorites were previously displayed even though there was nothing available to download. Also you can download using --url , it works.

It seems that Piccoma changed their URL, that's the issue and pretty easy to fix, we just have to wait the dev.

**Comment by MikeZeDev** [comment]
Endpoint for bookmark changed, __NEXT__ is now empty from bookmarks, hence the downloader wont work

https://piccoma.com/fr/api/haribo/fr/bookshelf/v2/bookmark

**Comment by Hachdog** [comment]
No news from the dev?

**Comment by MikeZeDev** [comment]
> No news from the dev?

People can use my fork in the meantime

* Download source, unzip it
* use command ```npm install && npm build && npm pkg``` in source folder to build the binaries
* look into dist folder for executables

**Comment by Hachdog** [comment]
> > No news from the dev?
> 
> People can use my fork in the meantime
> 
> * Download source, unzip it
> * use command `npm install && npm build && npm pkg` in source folder to build the binaries
> * look into dist folder for executables

Does it require to install Node?

**Comment by Elastic1** [comment]
Sorry for the delay. New release is published.
Thanks for the pull request @MikeZeDev

**Comment by Hachdog** [comment]
Thanks for the update
but...

![Capture](https://github.com/Elastic1/piccoma-downloader/assets/72262131/f890e5ff-1c8e-4d92-859b-c6f0b6025cf3)

**Comment by Hachdog** [comment]
> Sorry for the delay. New release is published. Thanks for the pull request @MikeZeDev

Thanks for the update
but...

![Capture](https://github.com/Elastic1/piccoma-downloader/assets/72262131/52cd8494-ba70-4d4f-bb31-8687b247200c)

**Comment by MikeZeDev** [comment]
> * folder

yeah forgot that . 

You can thanks Fairies he asked me and i was curious ;)
