### ISSUE TITLE
Login impossible

### ISSUE THREAD

**Issue by Akhilia** [Elastic1/piccoma-downloader#35]
Hello,
It seems that version 1.1.8 doesn't work for me...
When I try to log in, the window closes during the login phase.
I've tried to log in several times, thinking that I must have made a mistake with my identifiers, but this isn't the case (my old version logs me in even though I no longer have access to the chapters).
Does anyone have the same problem?

**Comment by DoctaEnkoda** [comment]
Try version 1.7

**Comment by Akhilia** [comment]
> Try version 1.7

Thx, it seems good for now :)

**Comment by Akhilia** [comment]
I close these.
Thx a lot
