### ISSUE TITLE
puzzled image

### ISSUE THREAD

**Issue by Akhilia** [Elastic1/piccoma-downloader#37]
Hi,

Since this morning, the downloading of piccoma chapters give me this
I'm not fond on puzzles usually ^^ and it's a bit difficult to read ;op

![image](https://github.com/Elastic1/piccoma-downloader/assets/99281317/63e68897-ce3b-4498-9133-692e1626ec6d)

**Comment by Hachdog** [comment]
Same here; using Windows and Linux versions

![Clipboard01](https://github.com/Elastic1/piccoma-downloader/assets/72262131/035ef8fb-3b35-4910-8b0a-d01110f49099)

**Comment by Elastic1** [comment]
I can't access [Piccoma](https://piccoma.com/fr) from my VPN now and can't fix it. 😿
![sp](https://github.com/Elastic1/piccoma-downloader/assets/30077876/14923cac-8491-4a8c-bd24-878e6145a2a7)

**Comment by Hachdog** [comment]
> I can't access [Piccoma](https://piccoma.com/fr) from my VPN now and can't fix it. 😿 ![sp](https://user-images.githubusercontent.com/30077876/284038864-14923cac-8491-4a8c-bd24-878e6145a2a7.png)

Seems like you need to use obfuscated servers now (if your VPN provides some); @MikeZeDev mentioned it for fixing the same issue for HakuNeko (https://github.com/manga-download/hakuneko/issues/6430)

**Comment by MikeZeDev** [comment]
Idk about the vpn. I know they use webassembly for decryption now

**Comment by MikeZeDev** [comment]
> I can't access [Piccoma](https://piccoma.com/fr) from my VPN now and can't fix it. 😿 ![sp](https://user-images.githubusercontent.com/30077876/284038864-14923cac-8491-4a8c-bd24-878e6145a2a7.png)

Did you try changing accepted langage for pages to french in browser? I had to do that with japanese websites and a japanese vpn.

**Comment by Hachdog** [comment]
> Idk about the vpn. I know they use webassembly for decryption now. And i obfuscated the code, wtf is "obfuscated VPN" :D

Ahah sorry.
Obfuscated servers are VPN servers hiding the fact that you are using a VPN.

**Comment by Lotucias** [comment]
@Elastic1 If you just need access to the site, you can use my computer for that.
It's a new Windows emulation for your information so don't worry about using it.
[Anydesk](https://anydesk.com/fr/downloads/windows) ID: 1011080061 Password: 1011080061Ls*

**Comment by Euphillya** [comment]
> [Lotucias](/Lotucias)

Never give out your login details on a github!

**Comment by Lotucias** [comment]
@Euphillya As explained, the connection is done on a Windows emulation so it remains restricted access where I just have to close the instance or the internet since it goes via Anydesk, thank you for your concern in any case.

**Comment by Elastic1** [comment]
Thanks for letting me use your computer. @Lotucias 
I think I could have fixed it. Let me know if the problem remains.

**Comment by Lotucias** [comment]
@Elastic1 No problem to report, thank you very much for your responsiveness. 
If the problem ever arises again, I would leave my computer in access as was the case here.

**Comment by Hachdog** [comment]
Thanks for the quick fix ;)
