### ISSUE TITLE
Cannot use charge to download manga

### ISSUE THREAD

**Issue by Yucie** [Elastic1/piccoma-downloader#39]
![Clipboard01fdsfdsf](https://github.com/Elastic1/piccoma-downloader/assets/12384865/32814b20-6ecb-4c35-ae2e-69fa25a39bef)

For example: 公爵様、その人は私のお兄ちゃんです！ have full charge but downloader cannot auto download manga with full charge anymore.

Please correct it. Thank you.

**Comment by Elastic1** [comment]
Thank you for report.
I'll fix it maybe tomorrow. ☺
