### ISSUE TITLE
タイトルが”？”が付いた時、フォルダ作成がエラーになりました。

### ISSUE THREAD

**Issue by Yucie** [Elastic1/piccoma-downloader#4]
error occurred. retry  [Error: ENOENT: no such file or directory, mkdir 'D:\piccoma\manga\【SMARTOON】こんなにビクビクしてるのにシないの？\3話 まだ…シ足りないの?一人エッチしてるのを見られちゃって…!?'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'D:\\piccoma\\manga\\【SMARTOON】こんなにビクビクしてるのにシないの？\\3話 まだ…シ足りないの?一人エッチしてるのを見られちゃって…!?'
}

タイトルが”？”が付いた時、フォルダ作成がエラーになりました。
よければ、修正してお願いします。

**Comment by Elastic1** [comment]
@Yucie  ご報告ありがとうございます。0.7.1にて修正しました
