### ISSUE TITLE
Images all scrambled

### ISSUE THREAD

**Issue by bensoc1** [Elastic1/piccoma-downloader#42]
![29](https://github.com/Elastic1/piccoma-downloader/assets/17823472/c7c3c99e-4149-4852-9ad2-cb0d3def9645)
hello,
when downloading chapters from piccoma every single image downloader is like this.
is it a bug on my side or piccoma that changed something ?

**Comment by Lotucias** [comment]
Looks like they should change their algorithm again.

@Elastic1 If you again need a computer with a French IP, here are the Anydesk IDs: 1564760547 / Lotucias*99

**Comment by Hachdog** [comment]
Just got out of my cave.
Any idea on how to fix this issue?

**Comment by Lotucias** [comment]
Here is the latest information for those who follow the post: 
Elastic1 was able to connect to the site but unfortunately, the scrambling algorithm has changed since the last update and it is now contained in a WebAssembly (Wasm) file.
His return by email seemed to say that it would be complicated to correct this time.
I hope he can get there but for now we can't count on it.

**Comment by Hachdog** [comment]
Thanks for keeping us posted.
Wasn't the last downloader version already using WASM, with the diamond.wasm file attached?

**Comment by Lotucias** [comment]
This is correct but the file WASM has been modified.
When Elastic1 connected to my emulator, he retrieved a similar file (WASM) but this produced an error with the software.
I don't know any more details, this is what he replied to me during our last exchange:
"It is not working very well. Probably hard to fix. The JP version has started using the same thing😨, so no need to log in again."
"Its just a scramble (problem). But one part of the process is hidden in a wasm file (binary format), which is difficult to read."
​

**Comment by Hachdog** [comment]
Should we summon @MikeZeDev ?

**Comment by Lotucias** [comment]
Any help is welcome ^-^

**Comment by MikeZeDev** [comment]
PiccomaJP started to to use the same WASM that PiccomaFR (well lets assume its the same). With some subtle variations  between both websites when it comes to "getting the parameters you need to feed to the WASM". 

* Javascript variable with page list has a different name between websites
* initial seed is a query parameter for one (?q=) and a part of the URL (/XXXXXX/) for the other
* Chapter viewer path is different.

Pretty sure Elastic1 figured it by himself and the problem is elsewhere.

**Comment by MikeZeDev** [comment]
Tried to fix that myself. I end up triggering "unreachable" error when i call the wasm dd function. At this rate, i have no clues.

**Comment by Hachdog** [comment]
Thanks for trying

**Comment by Elastic1** [comment]
I have successfully called the wasm dd function, but the return value seems to be different for some reason.

I could use a headless browser as a last resort, but distributing it as an exe is difficult.
If it is okay in the form of executing it with the node command (requires Node.js environment), I will release it as a separate repository.

**Comment by MikeZeDev** [comment]
BTW @Elastic1 when you try to check if the image is from french, i would use this regex if you dont mind. Because isfr ended up false when it had to be true while i tested

    ```
    const isFr = /cdn\.fr\.piccoma\.com/.test(url);
    const checksum = isFr ? new URL(url).searchParams.get('q') : getChecksum(url)
    const expires = new URL(url).searchParams.get('expires')
    const seed = getSeedInternal(checksum, expires)

 ```

**Comment by Lotucias** [comment]
I agree with @or-deal, as long as it is possible to download that's all that matters.
The only thing necessary will be to explain how to proceed in detail compared to the previous method.

**Comment by Hachdog** [comment]
Same as the others, as long as it works, I'll adapt

**Comment by TehUncleDolan** [comment]
Yeah, new WASM is a pain.
I also tried to use it in my own scraper, to no avail.
Either got the "unreachable" error or wrong values...

But where there’s a will, there’s a way :]
(for the FR version anyway, but likely the same for JP)

Can't say much more here in the open (the less they know about what we know, the better).
An hint though: less is more 😌

**Comment by TehUncleDolan** [comment]
This hand-crafted "magic" version produces the same output as my Rust scraper (which is working fine), so it should do the trick (for the French version, dunno about JP):
```js
const magic = 'AGFzbQEAAAABBgFgAn9/AAMCAQAFAwEAEQcPAgZtZW1vcnkCAAJkZAAACk0BSwECfwNAIAEgAkcEQEEBIAJ0QcfFxQFxRSACQRVLckUEQCAAIAJqIgMgAy0AACIDIANBAXRBAnFrQQFqOgAACyACQQFqIQIMAQsLCwA7CXByb2R1Y2VycwEMcHJvY2Vzc2VkLWJ5AgZ3YWxydXMGMC4yMC4zDHdhc20tYmluZGdlbgYwLjIuODk='

let wasm;

async function main() {
    const buf = Buffer.from(magic, 'base64')
    const res = await WebAssembly.instantiate(buf, {})
    wasm = res.instance.exports

    console.log(dd("TBSLV030DAZSA1PQ5I0CDC"));
}

function dd(seed) {
    const enc = new TextEncoder("utf-8");
    const bytes = new Uint8Array(wasm.memory.buffer, 0, seed.length);
    bytes.set(enc.encode(seed));
    wasm.dd(bytes.byteOffset, bytes.length)
    const dec = new TextDecoder("utf-8");
    return dec.decode(bytes);
}

main()
```

I never write JS so it's probably fucking ugly, but hopefully you get the idea.

**Comment by Lotucias** [comment]
@Elastic1 Great job, new version tested with previous parameters, works well.
Thank you so much.
