### ISSUE TITLE
Error when trying to have bookmarks

### ISSUE THREAD

**Issue by Lotucias** [Elastic1/piccoma-downloader#44]
Hello,

When trying to download today I get this error message and when trying with the url link it works so I guess it's the bookmarks that are the problem.

![Github](https://github.com/Elastic1/piccoma-downloader/assets/122485515/0b07cbeb-b794-4d11-9367-f6f6a960aaca)

Thanks for your help.

**Comment by Hachdog** [comment]
They changed the bookmarks url again?

**Comment by Hachdog** [comment]
It works. Thanks for the quick fix ;)
