### ISSUE TITLE
error downloading

### ISSUE THREAD

**Issue by Loyute** [Elastic1/piccoma-downloader#48]
Hello,
When I try to download, I get this error.
![Sans titre](https://github.com/Elastic1/piccoma-downloader/assets/73619901/3f9d30ec-0c55-4427-9f59-57c47be50f10)

**Comment by Akhilia** [comment]
Hello,

same here

![image](https://github.com/Elastic1/piccoma-downloader/assets/99281317/46b45cf2-20ea-4741-8c55-c13647ef6928)

**Comment by Lotucias** [comment]
@Elastic1 Mail sent as usual if you need.
