### ISSUE TITLE
saveEpisode error

### ISSUE THREAD

**Issue by Hachdog** [Elastic1/piccoma-downloader#49]
Hi everyone,
Got this error message this morning.
![Presse-papier01](https://github.com/Elastic1/piccoma-downloader/assets/72262131/aab24407-3181-484d-b2fc-16e4ac75ee69)

**Comment by Elastic1** [comment]
Already fixed [here](https://github.com/Elastic1/piccoma-downloader/releases/tag/v1.1.14).

**Comment by Hachdog** [comment]
> Already fixed [here](https://github.com/Elastic1/piccoma-downloader/releases/tag/v1.1.14).

Fastest Bug correction ever XD
Thanks dude

**Comment by Hachdog** [comment]
Is it just me or now the Gift Tickets work with this new version?
