### ISSUE TITLE
Guest mode

### ISSUE THREAD

**Issue by Ever4engel** [Elastic1/piccoma-downloader#6]
Hey is it possible to add guest mode for free chapters ?
with an option specifying the chapter link diurectly. 

and support all picoma domains the normal one https://piccoma.com/ and https://piccoma.com/fr/ it's the french part of the website. here a sample: https://fr.piccoma.com/fr/product/47

**Comment by Elastic1** [comment]
OK. I'll try to implement it.

**Comment by Elastic1** [comment]
You can now download chapter links like this.
`piccoma.exe --chapter-url https://fr.piccoma.com/fr/viewer/47/1423`

**Comment by Ever4engel** [comment]
> You can now download chapter links like this. `piccoma.exe --chapter-url https://fr.piccoma.com/fr/viewer/47/1423`

thanks for the support
