### ISSUE TITLE
Piccoma FR

### ISSUE THREAD

**Issue by cyberbad** [Elastic1/piccoma-downloader#9]
Can it working with the Piccoma fr website : https://piccoma.com/fr?

thanks

**Comment by Elastic1** [comment]
only supported for `--chapter-url` option.
Example:  `piccoma.exe --chapter-url https://fr.piccoma.com/fr/viewer/47/1423`

**Comment by Elastic1** [comment]
French version seems to have changed a lot since before.
Currently it is difficult to download and may not be supported.
